name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.14.0

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1

      - name: Build
        env:
          BASE_URL: /${{ github.event.repository.name }}/
        run: |
          pnpm install --frozen-lockfile
          pnpm run build -- --base=$BASE_URL

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
